-- DESAFIOS SOBRE ALTER TABLE

-- 1
ALTER TABLE locations
CHANGE ADDRESSSSS ADDRESS VARCHAR(40);

-- 2
ALTER TABLE regions
CHANGE REGION_NAME REGION VARCHAR(25);

-- 3
ALTER TABLE countries
CHANGE COUNTRY_NAME COUNTRY VARCHAR(40);